/*
	This program generate .MTH data that is a template file for Disag to generate .WTD file
	All parameters in MTH will be -99.0 meaning that
	Disag will generate data without constraints, using the parameters generated by eetimatePrm and recorded in a .PRM file.
	You may use it e.g. 

	genMth 2011 1 2012 12 > MEMU.MTH

	written by K. Honda 11 Sep 2015
*/
#include<stdio.h>
#include<stdlib.h>

#define	PROG	"genMth"

void usage( void )
{
	fprintf(stderr, "usage: %s start_year start_month end_year end_month > mthFile.MTH\n", PROG);
}

int main ( int argc, char **argv )
{
	int	startYear, startMonth, endYear, endMonth;
	int	year, month;

	if( argc != 5 ){
		usage();
		exit(1);
	}

	startYear  = atoi( argv[1] );
	startMonth = atoi( argv[2] );
	endYear    = atoi( argv[3] );
	endMonth   = atoi( argv[4] );

	if( startYear < 0 || startMonth < 1 || startMonth > 12 || endYear < 0 || endMonth < 1 || endMonth > 12
		|| startYear *100+startMonth >= endYear *100+endMonth ){
		usage();
		exit(2);
	}

	printf("@ StYr  StMn  SpYr  SpMn\n");
	printf("  %4.4d    %2d  %4.4d    %2d\n", startYear, startMonth, endYear, endMonth);
	/*     "  2011     1  2012    12" */
	printf("@ yr mo  srad  tmax  tmin  rain  pw   mui\n");
	year = startYear;
	month = startMonth;
	while( year*100+month <= endYear*100+endMonth ){
		printf("%4.4d %2d -99.0 -99.0 -99.0 -99.0 -99.0 -99.0\n", year, month);
		month++; if( month > 12 ) { year++; month=1; }
	}
	return 0;
}
/*
@ StYr  StMn  SpYr  SpMn
  2011     1  2012    12
@ yr mo  srad  tmax  tmin  rain  pw   mui
2011  1 -99.0 -99.0 -99.0 -99.0 -99.0 -99.0
*/
